name: ci

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Install project
        run: poetry install --no-interaction

      - name: Lint
        run: poetry run ruff check --diff .
      
      - name: Check formatting
        run: poetry run ruff format --diff .

      - name: Build
        run: poetry build
        
      - name: Run tests
        run: poetry run pytest
